## USB port
port: /dev/ttyACM0


##### Calibration ####
### accelerometer
accel_x_min: -255.86
accel_x_max: 252.93
accel_y_min: -252.32
accel_y_max: 256.84
accel_z_min: -259.16
accel_z_max: 262

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [-32.6634, -673.407, -490.930]
magn_ellipsoid_transform: [[0.708043, -0.00650448, -0.0163121], [-0.00650448, 0.956013, 0.0794459], [-0.0163121, 0.0794459, 0.853806]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: -0.01
gyro_average_offset_y: -0.01
gyro_average_offset_z: -0.02
